# Generated by Django 5.2.17 on 2026-08-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("froide_fax", "0004_faxoverride"),
    ]

    operations = [
        migrations.AddField(
            model_name="faxoverride",
            name="email_copy",
            field=models.EmailField(
                blank=True,
                help_text="If set, every message faxed to this public body is also sent to this address by email, as a separate message in the request thread.",
                max_length=254,
                verbose_name="email carbon copy",
            ),
        ),
    ]
